### ISSUE TITLE
error compiling IoTuz su ESP-WROVER-KIT

### ISSUE THREAD

**Issue by sfranchin63** [marcmerlin/IoTuz#1]
Hi Marc,
I tried to turn your firmware on ESP-WROVER-KIT but I got the following error.

ATTENZIONE: la libreria RobotIRremote dichiara di funzionare sulle architetture [avr] e potrebbe non essere compatibile con la tua scheda che utilizza l'architettura [esp32]
font.c:1: error: expected '=', ',', ';', 'asm' or '__attribute__' before '-' token
 Handheld-Color-Console/font.c
         ^
exit status 1
expected '=', ',', ';', 'asm' or '__attribute__' before '-' token
Can you help me
Thank you
Best regards
![error ili9341 arduinojpg](https://user-images.githubusercontent.com/23196408/27195101-ab28b11c-5205-11e7-9191-29a0e706706b.JPG)

Stefano

**Comment by marcmerlin** [comment]
It looks like your problem is with RobotIRremote
See https://github.com/z3t0/Arduino-IRremote/issues/431
Basically find RobotIRremote in your arduino installation, and remove it details in the bug above and in https://github.com/z3t0/Arduino-IRremote/issues/98

**Comment by sfranchin63** [comment]
Hi Marc,
I did as you suggested to me I deleted the RobotIRremote library and I put
that new one, but the error has remained.
I'm a beginner and I do not know where I'm wrong.
Thank you.
Stefano

2017-06-15 20:15 GMT+02:00 Marc MERLIN <notifications@github.com>:

**Comment by marcmerlin** [comment]
please compile with compiler debug warnings enabled and post the full output here.
However, please understand that I won't really have the time to help you with arduino basics. This is a reasonably advanced project on an advanced board.
If you haven't done arduino programming on AVR boards (and by that I mean you writing the code), I suggest you start there (sorry, I don't actually know what level you're at).

**Comment by marcmerlin** [comment]
I'm going to close this due to lack of followup
